name: Jobs

on:
  push:
  pull_request:

jobs:

  valgrind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install -y make 
          sudo apt install valgrind
          sudo apt-get install libssl-dev

      - name: Build project
        run: make

      - name: Create log directory (if necessary)
        run: mkdir -p log || true

      - name: Run Valgrind analysis
        run: valgrind --leak-check=full --suppressions=../../test/valgrind/suppressions.valgrind --show-leak-kinds=all --track-origins=yes --verbose --log-file=log/valgrind-log-github.txt ./imapcl

      - name: Check for memory leaks
        run: |
          if grep -q "ERROR SUMMARY: 0 errors from 0 contexts" log/valgrind-log-github.txt; then
            echo "No memory leaks detected."
          else
            echo "Memory leaks detected. Please check log/valgrind-log-github.txt for details."
            exit 1
          fi

      - name: Upload Valgrind report
        uses: actions/upload-artifact@v3
        with:
          name: valgrind-report
          path: log/valgrind-log-github.txt



  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install -y make 
          sudo apt install libgtest-dev

      - name: Run Tests
        run: make test  



  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Google Benchmark
        run: |
          git clone https://github.com/google/benchmark
          cd benchmark
          cmake . -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON
          make
          sudo make install

      - name: Run benchmarks
        run: |
          make benchmark

      - name: Analyze results
        run: |
          # Analyze the results 